### ISSUE TITLE
How to properly install?

### ISSUE THREAD

**Issue by LukvonStrom** [ftbastler/BoNeMEAL#1]
Please add a Description for what to do at the first run

//

Wir bekommen immer eine weiße Seite angezeigt beim ersten starten. Was ist beim ersten Start zu beachten/ zu machen ?

**Comment by ftbastler** [comment]
I think this issue is pretty similar to #2.

**Comment by ftbastler** [comment]
Check the wiki for installation instructions and try again with v1.0.
