### ISSUE TITLE
Issues with installing

### ISSUE THREAD

**Issue by Kakifrucht** [ftbastler/BoNeMEAL#10]
Hello,

I tried installing the framework, followed all steps, ensured that all modules are available.
Since I'm using nginx, I added the following to the config:
location /bonemeal {
    try_files $uri $uri/ /bonemeal/index.php?$query_string;
}
Whereas /bonemeal is my base dir.
I'm getting the "Whoops, looks like something went wrong." message with following stacktrace when trying to install: http://pastebin.com/Ug5rJXpq
however it shows up when not trying to install, too.

Do you have any ideas?

Thanks!

**Comment by ftbastler** [comment]
Seems like this is a webserver issue.

Do you have the PHP PDO sqlite support acitivated? The error 'could not find driver' is a strong hint on this.
Beware that sqlite support and pdo_sqlite are to different things.

**Comment by Kakifrucht** [comment]
Yes thanks, that was the case. I had to install the sqlite module.
It is now working ;)
