### ISSUE TITLE
Class 'App\Providers\PDO' not found

### ISSUE THREAD

**Issue by funniray** [ftbastler/BoNeMEAL#108]
**Describe the bug**
After adding my database, all I see is "Whoops, looks like something went wrong."

**Server Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - PHP Version: 7.2
 - Webserver: Nginx

**Log Files (you can use https://paste.ubuntu.com/ and post the link here):**
Please post your most recent log file if available.
https://paste.ubuntu.com/p/SGbG98x6dr/

**Comment by oranges13** [comment]
Hi there! Did you perform an upgrade or is this a new install?

**Comment by funniray** [comment]
This was a fresh install

**Comment by oranges13** [comment]
Ok thanks for this report! I will debug ASAP

**Comment by oranges13** [comment]
Hi there! I just pushed a new version that should fix this error. Please let me know if you have any questions or concerns.
