### ISSUE TITLE
Http Error 500 | Internal Server Error 

### ISSUE THREAD

**Issue by bigbluu722** [ftbastler/BoNeMEAL#111]
Hey there, 
I'm currently following the [installation guide](https://github.com/ftbastler/BoNeMEAL/wiki/Installation-and-Setup) and I've ran into an issue during installation. I'm receiving an internal server error. I've rewritten/tried the site without .htaccess but still get the same error noted above. Any assistance would be appreciated.

Distro/server information

Debian 10, running on apache2 v2.4.38 with all the required PHP modules. PHP v7.3.19.

-V

**Comment by oranges13** [comment]
Hi there! Is there any chance you could check the logs for an error?

Apache logs or inside the app directory under storage/logs

**Comment by bigbluu722** [comment]
Sorry for the delay, here's a line from the error.log in apache:
`[Mon Jul 20 21:42:15.089700 2020] [php7:error] [pid 21332] [client <redacted>:<redacted>] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/path/to/site/html/bans/application/storage/logs/laravel-2020-07-21.log" could not be opened: failed to open stream: Permission denied in /path/to/site/html/bans/application/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108\nStack trace:\n#0 /path/to/site/html/bans/application/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /path/to/site/html/bans/application/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /path/to/site/html/bans/application/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /path/to/site/html/bans/application/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\\Logger->addRecord(400, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /path/to/site/html/bans/application/vendor/laravel/framework/src/Illuminate/Log/Writer in /path/to/site/html/bans/application/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 108` 

If I'm reading the error log right, I would assume it has something to do with file permissions, not sure why that would be an issue though as I followed what was noted on the installation guide. 

EDIT: I've just rechecked it and the ``applications/storage`` folder does indeed have 0755 recursively set for itself and it's contents. The logs folder also doesn't seem to be logging anything either, not sure if the error points to anything noting why that would be as well.

-V

**Comment by oranges13** [comment]
Hi there,

The error indeed is that it cannot write to the storage directory. Double check the owner of the directory -- you may need to change the group or the owner to reflect the user running your apache installation. You may need to give the group higher access to the storage directory such as 0775 instead of 0755.

For example, here's my permission / user / group configuration

```
> ls -la storage
drwxrwxr-x  5 user group    86 Nov  1  2018 storage
```
```
>ls -la logs
drwxrwxr-x 2 user group  4096 Jul  7 13:27 logs
```

For now, from the `application` directory, try `chmod -R 775 storage` and see if that fixes the issue.

**Comment by bigbluu722** [comment]
I've seemed to of found the reoccurring issue here, I have the website directory owned under another user but the files are only read only to the group apache is currently in so apache cannot write it's files correctly. I've went ahead and fixed that for the time being. As that being fixed, I've ran into another issue but I'm not sure why. 


```
[2020-07-22 12:33:09] production.ERROR: PDOException: could not find driver in /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55
Stack trace:
#0 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(55): PDO->__construct('sqlite:/var/www...', NULL, NULL, Array)
#1 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/SQLiteConnector.php(37): Illuminate\Database\Connectors\Connector->createConnection('sqlite:/var/www...', Array, Array)
#2 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(60): Illuminate\Database\Connectors\SQLiteConnector->connect(Array)
#3 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(49): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(175): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'local')
#5 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(67): Illuminate\Database\DatabaseManager->makeConnection('local')
#6 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Support/Facades/Schema.php(18): Illuminate\Database\DatabaseManager->connection('local')
#7 /path/to/website/html/bans/application/app/Providers/AppServiceProvider.php(29): Illuminate\Support\Facades\Schema::connection('local')
#8 [internal function]: App\Providers\AppServiceProvider->boot()
#9 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#10 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#11 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AppServiceProvider))
#12 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\AppServiceProvider), 14)
#13 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#14 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#15 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#16 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(222): Illuminate\Foundation\Application->bootstrapWith(Array)
#17 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->bootstrap()
#18 /path/to/website/html/bans/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#19 /path/to/website/html/bans/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#20 {main}  
```

From what I can tell in this log, it's noting that I'm missing a module for it to work, but I have all of the required modules installed from what I can tell when checking an about page for PHP.

-V

**Comment by oranges13** [comment]
Can you answer these questions?

1. Did you download the most recent version of the software? If not which version did you get?
2. At what point in the process are you getting this error? Can you even get to the installation screen at all, or is this afterwards?
3. This application uses SQLite for it's local database but uses MySQL to access the minecraft databases. You'll need to make sure you have PDO installed for both in your PHP configs. If you can do a `php_info()` and confirm that you have both `pdo_sqlite` and `pdo_mysql` enabled that would help narrow down the issue.

**Comment by bigbluu722** [comment]
I grabbed the latest release as of 4 days ago when I made the ticket. This error pops up when I go to `mydomain.tld/bans/index.php/install`, it notes "whoops, something went wrong" when heading there. 

Looking at the phpinfo file for my configuration, I'm gathering I don't have pdo_sqlite installed as it only shows pdo_mysql when searching for it. How would I go about enabling/installing sqlite module for pdo? 

-V

**Comment by oranges13** [comment]
Depends heavily if you are on shared hosting or not. If so, you may need to contact your host, but you can try `sudo apt-get install php-sqlite3` or `sudo apt-get install php7.3-sqlite3`

**Comment by bigbluu722** [comment]
That seemed to have done the trick. I've successfully installed the panel and everything seems to be in working order. Thanks for the assistance. 

-V

**Comment by oranges13** [comment]
Awesome! I'm glad that we were able to get it sorted! I'll make sure to add a note to the wiki that you might have to check for those specific extensions!
