### ISSUE TITLE
Change actor of punishment to the current user when creating/editing

### ISSUE THREAD

**Issue by thu2468** [ftbastler/BoNeMEAL#12]
So like if i punish someone on BoNeMEAL than it by the name of the person that is log into BoNeMEAL

**Comment by ftbastler** [comment]
The problem here is that the actors of the plugin and the users of the app are to different things.
The app does not know which actor the current user is.

**Comment by LukvonStrom** [comment]
Maybe you could add a IP Match or something like that to make it clear for the app

**Comment by thu2468** [comment]
That prob wont work either. I thought you could have done something like a if this equal this than you can edit  this permissions when your a moderator or something like that

**Comment by thu2468** [comment]
How about this? Can you make it so that who ever makes a punishment with the web app, the actor will be the person login instead of it saying console is the actor. 
So for example Im login with the username Thu. I apply a punishment in the web app. It will say Thu apply the punishment in the history log

**Comment by thu2468** [comment]
Would my last comment work?

**Comment by ftbastler** [comment]
For that to work I would have to add a new player to the plugin's "players" table. However, for that I would need the UUID of the player.
I think an easier way to do that would be to add an "actor" input field to the create/edit punishments form...

**Comment by ftbastler** [comment]
As BoNeMEAL combines data from different servers, this is not really possible.
