### ISSUE TITLE
Latest Warnings/Notifications/Unbans incorrect

### ISSUE THREAD

**Issue by Kakifrucht** [ftbastler/BoNeMEAL#14]
In the admin panel, the Notifications show old warnings, and generally all of the dashboard information seems to be old. Latest unbans are one year old.
The active bans panel show all database information correctly, and the frontend does, too.

**Comment by ftbastler** [comment]
Could you see if that fixed it for you? Remember to flush your cache before you check.

**Comment by thu2468** [comment]
It seems to work

**Comment by ftbastler** [comment]
Thanks!
