### ISSUE TITLE
Make it possible to access player profile by username

### ISSUE THREAD

**Issue by Kakifrucht** [ftbastler/BoNeMEAL#16]
Right now, when accessing a players ban profile, you will need to supply the UUID, which is fine.
However BanManagement does not support UUID of a player in the messages.yml, which makes it impossible to rewrite the info-website-player translation.

Example:
Currently to access Notch's ban profile, you would need http://website.de/baseurl/players/069a79f444e94726a5befca90e38aaf5
how about enabling http://website.de/baseurl/players/Notch too?

**Comment by thu2468** [comment]
oh there work around for that use this.
    website:
      player: http://website.ca/bans/players/search?playername=[player]
This will work with the messages.yml

**Comment by Kakifrucht** [comment]
Nice thanks, that will work!

**Comment by ftbastler** [comment]
You can now use `/players/search/{playerName}`

**Comment by thu2468** [comment]
With this change it broke the search in the main page and the search in the admin page
