### ISSUE TITLE
With the latest update your search is broken

### ISSUE THREAD

**Issue by thu2468** [ftbastler/BoNeMEAL#17]
https://surl.im/i/g829s

**Comment by ftbastler** [comment]
Thanks, I just noticed that too. Will be fixed ASAP. ;)
Remember that I usually commit non-production ready code as well.

If you want to be safe, use one of the stable releases at https://github.com/ftbastler/BoNeMEAL/releases

**Comment by thu2468** [comment]
Yea xD. I added you on skype if that you. This way i can tell you bug asap

**Comment by thu2468** [comment]
Yea ik it stable and all. But it better to have tester to test and find bugs

**Comment by ftbastler** [comment]
That's right! Thank you btw for doing all that testing and stuff. ;)
