### ISSUE TITLE
Add "Toggle all" button for collapsed timeline items

### ISSUE THREAD

**Issue by thu2468** [ftbastler/BoNeMEAL#18]
Also can you put in like in the side of toggle detail if it a kick, ban, warning thanks

**Comment by thu2468** [comment]
Also it will be useful to have a Toggle All

**Comment by thu2468** [comment]
So something like this http://prntscr.com/7520td

**Comment by ftbastler** [comment]
You can just look at the icons on the timeline, right?

**Comment by thu2468** [comment]
I guess so. But the toggle all would be nice to have and the left side doesnt seem to be working though

**Comment by thu2468** [comment]
https://surl.im/i/v33gd
