### ISSUE TITLE
Setup Guide?

### ISSUE THREAD

**Issue by TomLewis** [ftbastler/BoNeMEAL#2]
I have no idea how to set this up on my web-server; The main directory looks like it shouldn't be there as there is no index.php and the htacess denies all requests to that page, when I run /public it fails with:

Parse error: syntax error, unexpected '[' in /Applications/AMPPS/www/bonemeal/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 49

**Comment by ftbastler** [comment]
Setup guide is available here: https://github.com/ftbastler/BoNeMEAL/wiki/Installation-and-Setup

**Comment by ftbastler** [comment]
Check #1
