### ISSUE TITLE
The toggle doesn't appear on some of the logs. I think it only on the warnings.

### ISSUE THREAD

**Issue by thu2468** [ftbastler/BoNeMEAL#20]
Here how it looks like https://surl.im/i/6vjmn

**Comment by ftbastler** [comment]
Nope, that is correct.
The toggle only appears if the expired ban/mute record is older than 30 days and for warnings, notes and kicks only if they are older than 60 days. Active bans and mutes will not be collapsed.

**Comment by thu2468** [comment]
Oh ic
