### ISSUE TITLE
Removing ban/mute does not unban/unmute the player

### ISSUE THREAD

**Issue by thu2468** [ftbastler/BoNeMEAL#21]
Removing a ban doesnt unban the player

**Comment by ftbastler** [comment]
This might be a restriction of the Ban-Management plugin.

**Comment by thu2468** [comment]
What kind of info needed?

**Comment by ftbastler** [comment]
@confuser Why does the ban not get removed when it is no longer in the database?

**Comment by confuser** [comment]
You need to insert the ban into the ban records table, as that's what the
plugin looks for when syncing unbans.

**Comment by ftbastler** [comment]
Thanks!
