### ISSUE TITLE
The icon for an active mute/ban does not show as "active"

### ISSUE THREAD

**Issue by thu2468** [ftbastler/BoNeMEAL#25]
https://surl.im/i/oyz3b

**Comment by ftbastler** [comment]
What's the problem?

**Comment by thu2468** [comment]
Isnt the ban icon above punish suppose to be active?

**Comment by ftbastler** [comment]
Don't get confused about it being gray. It actually just shows up when a player is banned/muted.

**Comment by thu2468** [comment]
But why is it showing both icon when the player is only ban? That player isnt muted

**Comment by ftbastler** [comment]
Show me some more info about that player...

**Comment by thu2468** [comment]
Like for example this https://surl.im/i/i6tkf. The mute icon is there and it say currently muted but if you look at the logs he/she isnt muted but is banned only
Do you get what im saying now?

**Comment by ftbastler** [comment]
Ok, that is strange. Will fix.
