### ISSUE TITLE
Make it possible to delete expired ban/mute records

### ISSUE THREAD

**Issue by thu2468** [ftbastler/BoNeMEAL#26]

**Comment by ftbastler** [comment]
I don't really get what you mean. The Ban-Management plugin is actually setup to keep a "record" of expired mutes and bans. This is also useful to see the criminal history of a player.

**Comment by thu2468** [comment]
Im just thinking like if a staff staff has wrongfully ban/mute some you should be able to delete that record

**Comment by ftbastler** [comment]
Okay, I will think about this.
