### ISSUE TITLE
Shorten the load time on specific pages

### ISSUE THREAD

**Issue by thu2468** [ftbastler/BoNeMEAL#28]
Shorten the load time on example.com/bans/admin/players & the load time when you go into admin panel. 

The new graph is making it load slowly in the dashboard. So maybe move it to another tab? Like something called Statistics. Or cache the stats?

**Comment by thu2468** [comment]
The new graph is making it load slowly in the dashboard. So maybe move it to another tab? Like something called Statistics

**Comment by thu2468** [comment]
and maybe move the update check bellow the activity

**Comment by ftbastler** [comment]
You really have to learn how to create proper issues. This is really getting annoying...
Thanks anyways for letting me know. :)

**Comment by thu2468** [comment]
Sorry :/ Just not use making threads
