### ISSUE TITLE
Accessing /install results in error 404

### ISSUE THREAD

**Issue by xtechgamer735** [ftbastler/BoNeMEAL#29]
When going to mydomain.tld/BoNeMEAL I get redirected to the /install directory which is a 404. I am running PHP version 5.4 and all the required extensions (which are up to date). 

There is no error log in the /storage/logs folder.

Thanks,

**Comment by ftbastler** [comment]
Error log please. See https://github.com/ftbastler/BoNeMEAL/wiki/Reporting-issues

**Comment by xtechgamer735** [comment]
I have updated the issue accordingly.

**Comment by ftbastler** [comment]
Well, that is strange. I saw that you first couldn't get the installation to work - then it worked - and then it failed again, so maybe try with a fresh install.

**Comment by xtechgamer735** [comment]
Yes, I was having a few issues with PHP. I was on 5.3, so I upgraded to 5.6 and it had a mcrypt key size error (The sorry there was an error message). After some googling it appeared that it was a known issue so I backdated to PHP version 5.4 which I am running now. The only one I haven't tried is 5.5, is that worth a shot?

Also I'm running CentOS, would a different distro work better?

Thanks.

**Comment by ftbastler** [comment]
Maybe this could help you: https://iamtrishulpani.wordpress.com/2014/10/21/installing-and-using-laravel-4-2-on-centos-6-5/

Just try to google "Laravel" / "Laravel 5" with "CentOS" or "PHP 5.4". This does not seem to be an issue related to BoNeMEAL as it works fine for me...

**Comment by xtechgamer735** [comment]
That looks good thanks, Ill give it a go. As you say its probably not a BoNeMEAL issue, just my server being awkward.

Thanks!

**Comment by xtechgamer735** [comment]
Ok, we kind of have lift off. I am getting a "Whoops, looks like something went wrong." now. Here is my log file: http://pastebin.com/bThXpwEt Running PHP 5.6 with all required dependancies. Followed the guid you gave me, just had to install composer separately.

Thanks,

Tech.

**Comment by ftbastler** [comment]
Be sure that in your `.env` file the APP_KEY is exactly 32 characters long.

**Comment by xtechgamer735** [comment]
Done that thanks, once again getting a 404 for /install with no error message in the logs.

**Comment by ftbastler** [comment]
Ok, this really starts to become weird and I am running out of ideas.
Can you access `<base url>/index.php/install`? (Notice the **index.php**)

**Comment by xtechgamer735** [comment]
Yes I can get there no problem. Thanks.

**Comment by ftbastler** [comment]
Ok, seems like **mod_rewrite** does not work for you (maybe you don't run Apache?). You will have to find out yourself how to manipulate URLs with the server software you are running. Google might help you with that.

**Comment by xtechgamer735** [comment]
Great stuff, thanks for your help!
