### ISSUE TITLE
"Banned/muted" icons show even when not punished

### ISSUE THREAD

**Issue by ftbastler** [ftbastler/BoNeMEAL#30]
The icons on a player profile for "banned" or "muted" show even when the player is not punished.
See: http://p-x.ca/bans/players/af3f1641d1e94c19aeda30fb223f97f3

**Comment by ftbastler** [comment]
This does not happen on my test server...

Can anyone confim this?

**Comment by ftbastler** [comment]
This does not happen on my test server...

Can anyone confim this?

**Comment by pprice-io** [comment]
This does not happen on my server.

**Comment by gardenerik** [comment]
This is happening on our banlist (maybe because I cleared bans database).

**Comment by ghost** [comment]
Can confirm this happens, it's currently happening to myself.

**Comment by ftbastler** [comment]
Thanks for the feedback.

**Comment by acidbyt3** [comment]
This is happening to me. Was this issue ever fixed/any workaround available?
http://icecraftnation.com/bans/index.php/players/c0b01ebe89c64820909fa4d3bdafa68a

I can't find any info on this anywhere.

**Comment by Legoman99573** [comment]
Happened on fresh install in the past. Can confirm the bug.

**Comment by Maxetto** [comment]
Happened on fresh install for me.
I've just imported bans.

**Comment by oranges13** [comment]
A cursory examination into why this is occurring is that on `PlayerController::show`, `$activeBans` is being filled with all of the active bans for the entire server.

If you `dump($activeBans)` on player.blade.php I get the total number currently active on our server despite the fact that the currently viewed player is not banned or muted. Working on a PR to fix.
