### ISSUE TITLE
Admin Dashboard Error?

### ISSUE THREAD

**Issue by itismejoey** [ftbastler/BoNeMEAL#33]
Keep getting an "Whoops, looks like something went wrong" message when I try to go to the Admin Dashboard.

http://pastebin.com/rLxznBM1

**Comment by Townville** [comment]
Error at the log: "Base table or view not found" and 'mcfriend_bm.bm_player_notes' doesn't exist'

**Comment by itismejoey** [comment]
Ahhh it's quite possible its because I am testing off a backup and I think I downloaded that before I updated to the version with notes. Thanks so much!

**Comment by ftbastler** [comment]
Yep, that is causing the error. Be sure you have the latest database structure.
