### ISSUE TITLE
Ideas for Bonemeal

### ISSUE THREAD

**Issue by arriej** [ftbastler/BoNeMEAL#34]
Hey, 
I am not sure if you had this in the planning to add,
But i think its a good idea to add, kicks, warnings and ip bans to the Punishment type split.
now it only contains bans and mutes. 

Also an other idea  When a temp ban has past maybe its a good idea to add How long the temp ban was, (i am not sure if this is information you can get out of the database. )
Awesome work tho keep it up!

**Comment by ftbastler** [comment]
Thanks. I will see what I can do.
