### ISSUE TITLE
Error 404 when trying to access app on nginx

### ISSUE THREAD

**Issue by lucasdidur** [ftbastler/BoNeMEAL#35]
When I try to install, the install page is not found. What could be?

**Comment by arriej** [comment]
make sure you have set the good RewriteBase in the .htaccess file. 
for me because i installed it on a bans.blockmadness,com as a subdomain my RewriteBase is just / 
but if i would install in on blockmadness.com/ban my RewriteBase would be /ban/

**Comment by lucasdidur** [comment]
I think that is the problem, i use nginx, did you know what i should do?

**Comment by arriej** [comment]
yeah sorry, but i am not able to help you. I never used nginx. 
but it seems most likely something is with the mod_rewrite that Apache uses. I´d say give google a shot. 

"If your webserver is running Apache then mod_rewrite should be installed. If you do not run Apache you will have to find out yourself how to manipulate URLs with your server software."

EDIT: Have a look at this? maybe it can help you out: http://serverfault.com/questions/373079/nginx-rewrite-base-url

EDIT2: also this: http://laravel.com/docs/5.0#server-requirements then scroll down till you see "Pretty URLs" there is info about Nginx

**Comment by lucasdidur** [comment]
I found, on my nginx i put this configuration and works. Thank you.

```
location /bans/ 
{
	rewrite ^/(.*)/$ /bans/$1 permanent;
	try_files $uri/ $uri /bans/index.php$is_args$args;
}
```

**Comment by ftbastler** [comment]
I never used nginx so I can't really help you with that. Have a look at the links and search on Google - that might help you.
