### ISSUE TITLE
Cant install from a sub-directroy 

### ISSUE THREAD

**Issue by TomLewis** [ftbastler/BoNeMEAL#36]
Im assuming this is a .htaccess error, Im trying to install this from a sub-directroy, and I cant get to the install page, Im trying to run it as a test at first to make sure it works/is safe. This is a very odd way having a folder (applications) that is not secure, I don't understand why this needs to be included or isn't protected out the box, so Im wary of using this and want to test it first. 99.9% of all PHP scripts I've ever used over 10 years haven't needed to hide a folder for security reasons, they are designed to be safe from the get go.
It will be located at bans.piratemc.com, currently running the old V4 system, For testing im trying to install at:
http://stats.piratemc.com/bonemeal/install
But it won't load the install, im assuming as the htaccess isn't setup to work with sub-directories?

**Comment by ftbastler** [comment]
You could say the application folder holds the whole backend of the app. It also includes a SQLite database, some configuration files and other stuff. Normally you would install Laravel on your server and then have a `public` directory to which you would route your webserver.
The problem is most server owners have a shared host or don't have to knowledge to do that. That's why we have the application folder. Just make sure to tell your webserver to deny requests to that directory and you are all good.

If you run Apache, make sure you set the `RewriteBase` in your `.htaccess` file. If you are using nginx you might find help over at #35.

**Comment by TomLewis** [comment]
Ahh Right, gotcha.
As for using a sub-directory folder I just get a 500 internal server error when I set the sub-domain to the RewriteBase in htaccess, I tried with http:// and without it, I tried it with the folder-name and without, all 500 Internal Server Error.
Are you sure you can set a sub-domain that way in htaccess? I even tried the full path, no dice.

**Comment by ftbastler** [comment]
Don't use the directory path, but the URL to where you installed...

**Comment by TomLewis** [comment]
Yeah I did, that's what created the 500 internal server error, Like I said I tried with and without the http://

**Comment by ftbastler** [comment]
So you use Apache? Let me see what you got in your `.htaccess` file.
Can you access `<base url>/index.php/install`? (Notice the index.php)

**Comment by TomLewis** [comment]
Yeah I use Apache. No I cant access that url since anything in that directory is 500 internal server error...
As I've said I tried variants of changing the RewriteBase like you suggested, for example:
The url is stats.piratemc.com/bonemeal
I have tried:
RewriteBase stats.piratemc.com 
RewriteBase stats.piratemc.com/bonemeal
RewriteBase http://stats.piratemc.com 
RewriteBase http://stats.piratemc.com/bonemeal
RewriteBase /
RewriteBase /bonemeal

**Comment by ftbastler** [comment]
Ok, you don't have any error logs and you do fulfill all requirements?
Edit: Just looked at your webpage and might found the problem. I think you already re-write your URLs,  don't you? Do you have a `.htaccess` file in your webpage's root directory? That might be it...

**Comment by TomLewis** [comment]
No error logs, all requirements, yes.

**Comment by minegame30** [comment]
Not sure if this helps at all. Error 500 is generally (not always) related to permissions and being unable to access files.
When you unzipped the Bonemeal file, and it placed it in the bonemeal folder, I moved it out of that folder directly into my subdirectory folder. Then, you just need to set your rewritebase to /

 Check your permissions are correct. I ~BELIEVE~ all files (such as index.php) need to have the permissions of 0644 whereas folders (so the folder itself, not the contents) needs to have 0775.
I just changed the permissions of my index.php and recieved the 500 error. Chances are, its permissions.
(The error I got when I changed the permissions)
![image](https://cloud.githubusercontent.com/assets/11843354/8069543/28ccc66a-0ef3-11e5-9d18-6ccce1a9416d.png)

**Comment by TomLewis** [comment]
Files and folders are 0775; I set a recursive permission change on all folders/documents to 0775 just to make sure, and nothing changed.

**Comment by ftbastler** [comment]
Hmm... this is strange. What is your `phpinfo()` output?

**Comment by TomLewis** [comment]
http://mediasmoke.co.uk/phpinfo.php

**Comment by minegame30** [comment]
If you want, I can try to run it on my webserver which I know works? If you want, just zip up the files and post them here and ill upload it and see?
It might be your webserver is setup incorrectly or something.

**Comment by ftbastler** [comment]
Did you try installing BoNeMEAL in the root directory for testing?

**Comment by ftbastler** [comment]
Any news on this?
