### ISSUE TITLE
Add some configuration options for admins

### ISSUE THREAD

**Issue by minegame30** [ftbastler/BoNeMEAL#37]
Hi,

This isn't an issue with the project as such.
I have had a brief look through the files and cannot seem to be able to find this. I'm probably looking straight over it as well.

How would I go about changing the title of the BoNeMEAL pages? Which file is this located in?

And how would I go about changing the  "Am I being detained?!" on the front page? Again, which file is this located in?

As an idea, if you would like, you could add this to the configuration section of the admin panel (to allow users to change it without having to go searching for config files)

Thanks :)

**Comment by minegame30** [comment]
Update, I found the configuration files (turns out they were all hidden in the language EN folder here: application/resources/lang/en)
However more config options is definitely a good idea as so people do not have to hunt around to find things.

**Comment by ftbastler** [comment]
These are NOT the configuration files. That are the language/translation files and you should **not** touch them, as they will be overridden with every update and a translated phrase could be used in different contexts where your customized message would not make sense.

**Comment by minegame30** [comment]
Hi,
Yeah that is what I meant. (Language files)

I understand what you are saying about not touching them, however I am aware of the risks following an update and only needed to make a small change. If anything breaks, or doesnt make sense, ill just restore the file from a backup.

**Comment by ftbastler** [comment]
@minegame30 The file changes all the time. I will add proper configuration options very soon.

**Comment by pprice-io** [comment]
This would be a good implementation as many people may look around for hours trying to find the places to change all of these options.

**Comment by ftbastler** [comment]
Started to implement this...
