### ISSUE TITLE
 syntax error, unexpected '['

### ISSUE THREAD

**Issue by rcs2112** [ftbastler/BoNeMEAL#38]
After uploading the files to a directory in my webserver's FTP, I get a parse error.

"Parse error: syntax error, unexpected '[' in /home/chimerag/public_html/bans/application/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 49"

I checked the file out and it appears to be  `function app($make = null, $parameters = [])` that causes the problem.

**Comment by ftbastler** [comment]
Which version of PHP are you running? What server software do you use?
Did you check all requirements?

**Comment by rcs2112** [comment]
It appears I am being forced to use a disgustingly old version of PHP. 5.3.29. Is this my problem?

It's an Apache server.

**Comment by ftbastler** [comment]
That might be the reason. Check if you meet the requirements over [here](https://github.com/ftbastler/BoNeMEAL/wiki/Installation-and-Setup#pre-installation).
