### ISSUE TITLE
White page after installing?

### ISSUE THREAD

**Issue by thu2468** [ftbastler/BoNeMEAL#4]
So i have the thing in /home/www/html/banlog2 i changed RewriteBase /home/www/html/banlog2 to that. i went to http://website.ca/banlog2/ and http://website.ca/banlog2/install and it is blank. What am i doing wrong?

**Comment by Vidsify** [comment]
I think a more detailed install/setup tutorial is needed. Have you tried the normal Ban Manager WebGUI?

**Comment by thu2468** [comment]
yes but i thought this was interesting and wanted to give this a try

**Comment by ftbastler** [comment]
Try to set your RewriteBase to `/banlog2` instead of `/home/www/html/banlog2`.

**Comment by thu2468** [comment]
hm it still doesnt work. Do you think we can skype or something?

**Comment by thu2468** [comment]
Is there anything that im doing wrong or forgot to do?

**Comment by thu2468** [comment]
Ok it looks like a fix the issues. i had to change the folder permissions and sqllite.

**Comment by ftbastler** [comment]
Ok, thanks. I wasn't aware that would be an issue. I will add that to the installation instructions.

**Comment by ftbastler** [comment]
Could you describe exactly what you did? E.g. for which folders you had to change permission?

**Comment by thu2468** [comment]
i had to make apache2 the owner of the folder so like chown -R www-data:www-data /home/www/html/bans/*

**Comment by EvilOlaf** [comment]
So the solution would be the same as giving `777` permission to these folders which might be from a security point of view not a good idea. Only folders where a script actually really needs write permissions should have appropriate permissions set. 

The majority of the users will have no shell access to their webhosting server, so they can not do a `chown` on their home directory which is surely also not wanted by the provider.
