### ISSUE TITLE
Admin page loading really slow or failing to load

### ISSUE THREAD

**Issue by thu2468** [ftbastler/BoNeMEAL#40]
This is the error 
[2015-06-15 03:46:00] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 12353016 bytes)' in /home/www/html/bans/application/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:99
Stack trace:
#0 {main}

[2015-06-15 03:47:10] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 12353016 bytes)' in /home/www/html/bans/application/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:99
Stack trace:
#0 {main}

[2015-06-15 03:51:07] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 12353016 bytes)' in /home/www/html/bans/application/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:99
Stack trace:
#0 {main}

[2015-06-15 16:50:13] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 12378661 bytes)' in /home/www/html/bans/application/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:99
Stack trace:
#0 {main}

**Comment by ftbastler** [comment]
Go to the `index.php` file and add `ini_set('memory_limit', '1024M');` or similar to increase your PHP memory limit. Alternatively, you can also use a `php.ini` file and set that value.

**Comment by EvilOlaf** [comment]
Maybe a stupid question, but isn't 1GB quite a hugh amount of memory for a php script?

**Comment by ftbastler** [comment]
Yeah, you will not need _that_ much... :stuck_out_tongue_winking_eye:

**Comment by thu2468** [comment]
So Like this?

```
<?php
/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylorotwell@gmail.com>
 */

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels nice to relax.
|
*/

require __DIR__.'/application/bootstrap/autoload.php';

ini_set('memory_limit', '1024M');

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once __DIR__.'/application/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

$kernel = $app->make('Illuminate\Contracts\Http\Kernel');

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);
```

**Comment by thu2468** [comment]
Like i can log in but when i try to go into admin panel it times out and say that error

**Comment by ftbastler** [comment]
Yes, that should do it.

**Comment by thu2468** [comment]
Hmm sometime it loads sometime it doesnt load the admin panel. Like sometime there will be a long load then it will connect and then sometime its a long load then crash

**Comment by ftbastler** [comment]
How many servers did you add to BoNeMEAL?

**Comment by thu2468** [comment]
Just 2

**Comment by ftbastler** [comment]
What are your server specs? They might be a bit low...

**Comment by thu2468** [comment]
This is the server spec http://www.ovh.com/ca/en/dedicated-servers/enterprise/2014-SP-64.xml

**Comment by ftbastler** [comment]
Well, that should be plenty of specs... I might add some measuring so we can find out what's taking so long to load the page.

**Comment by thu2468** [comment]
Hm can you create a account on your thing and i can set you to a moderator
This way you can see what is going on. And test if you also have a long load
Also you can hit me up on skype: thu2468

**Comment by thu2468** [comment]
Ok i have set you to moderator. Do you have any issue on connecting to the admin panel dashboard?

**Comment by thu2468** [comment]
Have you figured out what is wrong yet?

**Comment by ftbastler** [comment]
No, sorry - not yet.
Could you maybe go into your `.env` file and set `APP_DEBUG=true`?

**Comment by thu2468** [comment]
Ok i have added the option in application/.env

**Comment by thu2468** [comment]
Foudn anything yet?

**Comment by ftbastler** [comment]
It might be because of your large number of database entries. What happens when you remove one server? Does it load faster?

**Comment by thu2468** [comment]
It loaded with one server, but it still pretty long load. But didnt throw error

**Comment by thu2468** [comment]
It was loading faster before a couple of updates before the latest one. could it be possible that the statistic in the dashboard causing the slow load. as it is getting data from every players every time.

**Comment by thu2468** [comment]
But is there a fix for this as it shouldnt load this long even when having one server

**Comment by thu2468** [comment]
So have you found a fix yet?

**Comment by thu2468** [comment]
like it seems to only happen in p-x.ca/bans/admin because i can go to http://p-x.ca/bans/admin/users just fine and loads fast

**Comment by Torbikini** [comment]
I've been having this issue too. I can directly visit https://bans.simplecraft.us/admin/users but if I try https://bans.simplecraft.us/admin it just says "Whoops, looks like something went wrong". However this notification is instant compared to your situation.

**Comment by ftbastler** [comment]
Can you post the laravel log file and your webserver log error message?
