### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by SystemDan** [ftbastler/BoNeMEAL#42]
Hey so I'm trying to install this and every time I load where the website is, it tries to load /root/install which is displaying a 404 error. After checking the zip file provided on your github, there does not seem to be an install folder.

**Comment by ftbastler** [comment]
BoNeMEAL runs on Laravel, a php framework. The URLs won't match the folder structure.

Be sure to [read the wiki](https://github.com/ftbastler/BoNeMEAL/wiki/Installation-and-Setup) to setup this app.

**Comment by SystemDan** [comment]
Okay so I realized that I can't install it using a different directory i.e domain.tld/checkbans but is there anyway to change it so that I can?

**Comment by ftbastler** [comment]
You can, you will just have to set the RewriteBase in your `.htaccess` file, assuming you are running Apache.

**Comment by SystemDan** [comment]
I got it fixed. Thanks so much!
