### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by ZR2** [ftbastler/BoNeMEAL#43]
I have installed Laravel and all of the requirements and still can't get it to install I have changed the RewriteBase but when I go to the install page it's blank.
-Thanks Josh

**Comment by ftbastler** [comment]
What exactly did you do?

**Comment by ZR2** [comment]
Well first I installed all the php extensions then composer then Laravel but can't get it to work

**Comment by ftbastler** [comment]
Don't install Laravel - install BoNeMEAL... ;)

**Comment by ZR2** [comment]
Wait what?

**Comment by ftbastler** [comment]
Follow the installation instructions. You don't need composer or Laravel.
All you need to download is BoNeMEAL from here: https://github.com/ftbastler/BoNeMEAL/releases

**Comment by ZR2** [comment]
Wait what.....

**Comment by ftbastler** [comment]
It's easy. Just follow this tutorial: https://github.com/ftbastler/BoNeMEAL/wiki/Installation-and-Setup

**Comment by ftbastler** [comment]
Did you get it?
