### ISSUE TITLE
No install directory???

### ISSUE THREAD

**Issue by Agazed** [ftbastler/BoNeMEAL#44]
I am very confused on how to setup this and when I go to <myurl>/bonemeal/install, there is no actual directory.

How do I set up the RewriteBase you mentioned?

Is the wiki not updated or am I a complete dumbo?

**Comment by ftbastler** [comment]
BoNeMEAL runs on Laravel, a php framework. The URLs won't match the folder structure.

To set the RewriteBase check your `.htaccess` file, assuming you are running Apache. The wiki installation page is pretty clear I think.

**Comment by Agazed** [comment]
What do I do with the .htaccess file? Do you have an example on what it should look like? And yes, i'm running Apache.

Sorry i'm a complete rookie on this stuff.

**Comment by ftbastler** [comment]
The `.htaccess` file comes with BoNeMEAL. Read the wiki installation instructions...
If you want to install BoNeMEAL in a subfolder, then you will have to change the RewriteBase in that file.

If don't have any experience with server configuration try the noob-friendly [WebUI](https://github.com/BanManagement/BanManager-WebUI)

**Comment by Agazed** [comment]
Okay ive managed to install Laravel correctly and this is my .htaccess file https://gist.github.com/Agazed/965a001fd9d614489746

My url to Bone Meal is bans.skylair.net/BoNeMEAL

bans.skylair.net/BoNeMEAL/install is still not working. Any idea on what to do?

**Comment by ftbastler** [comment]
Do you meet all requirements?
http://bans.skylair.net/BoNeMEAL/index.php should work if you have installed it correctly.

**Comment by Agazed** [comment]
Ugh ive been working on this for a couple hours now and I cant seem to find my issues. Too complicated. You should make this work out of the box just like the WebUI.

Too many dependencies and I am pulling my hair out on how to just make this work.

**Comment by ftbastler** [comment]
Actually, it's pretty easy if you have basic knowledge of hosting a webserver...
The wiki installation guide is pretty straight forward - it's really not a big deal.
