### ISSUE TITLE
Error when removing ban

### ISSUE THREAD

**Issue by ghost** [ftbastler/BoNeMEAL#45]
http://pastebin.com/ugw5dU60

When clicking 'remove' I get this error.

**Comment by ghost** [comment]
`$record->actor_id = \App\Player::on($server->id)->where('name', '=', 'Console')->firstOrFail()->id;`

To fix, I changes Console to Server. Maybe it's a Cauldron thing v0v

**Comment by ghost** [comment]
Is it not possible to detect the console user or have a config for it?

**Comment by ftbastler** [comment]
The question is, why is your console player not named Console?

**Comment by ghost** [comment]
No idea, I assume it's down to vanilla MC/Forge/Cauldron or something.

**Comment by ftbastler** [comment]
That should not be the case. Which version of Ban-Manager are you running?

**Comment by ghost** [comment]
5.5.0
