### ISSUE TITLE
Console kicks gives 404 page

### ISSUE THREAD

**Issue by arriej** [ftbastler/BoNeMEAL#46]
Hey,

So when the server auto kicks someone for example spamming it shows up in the history list in the admin panel. 
![a1e88cf5f3ea16fa9c7520f5a25fb606](https://cloud.githubusercontent.com/assets/1354079/8565559/faf49c5c-2556-11e5-9c16-b0c0b35c1968.png)
When you click on that warning you get a 404 page, with an odd url. The url looks like this: http://bans.blockmadness.com/admin/kicks/2/5 and this trows a 404 page. 

But when you go to page of the user it self they are stated there: 
![fcd8c6ca941b007ddf2d13d03ab28fc6](https://cloud.githubusercontent.com/assets/1354079/8565577/38fff49c-2557-11e5-8a10-81421b9e9110.png)

;) Hope that this is enough information.

**Comment by ftbastler** [comment]
Thanks for the info. Will look into this.

**Comment by ftbastler** [comment]
Fixed.
