### ISSUE TITLE
stattics page does not load without bm_ip_bans table.

### ISSUE THREAD

**Issue by arriej** [ftbastler/BoNeMEAL#47]
So i just noticed this (accidently deleted a beginning database) 
You need table the table "bm_ip_bans"  Tho this table is not created by the new versions of ban manager (maybe it creates it when you ip ban someone) But it looks like its an old table from older ban management before the uuid update. 

Get the following stacktrace without the table: http://paste.ubuntu.com/11889806/

Not sure if the issue of not creating with ban manager or its an old database. 
just letting ya know ;)

**Comment by ftbastler** [comment]
This seems odd... Try to run the latest version of the Ban Manager.
