### ISSUE TITLE
Blank install page 

### ISSUE THREAD

**Issue by AshourAziz** [ftbastler/BoNeMEAL#48]
Hey so the directory is https://cityprison.net/newbans/
and our .htaccess contains:
RewriteBase /newbans

If I'm not mistaken I'm spot on, I'm running the latest zip 1.1.0 :)

**Comment by ftbastler** [comment]
Hmm... do you run Apache and do also you have an `.htaccess` file in your root directory?

**Comment by ziutekkk** [comment]
I have same problem too..
I am sure that I have installed all required extensions.
Here is my .htaccess file: http://pastebin.com/KGf42pa5
After all required steps all I get is blank page. Maybe it is something related to apache 2.4?
I dont know. Thanks

**Comment by yannicktf** [comment]
Be sure your /application/storage directory is readable and writeable

**Comment by CHarrisMedia** [comment]
Same issue, I have both things above done. There is just no install.php or install folder in the root directory?

**Comment by pprice-io** [comment]
Have currently got the same issue once i tried to reinstall on a new webserver.

**Comment by mibby** [comment]
@ftbastler I also seem to be having this problem. The main directory is a blank page (on firefox, chrome reports server error 500). Which results in `/BoNeMEAL/index.php/install` being a blank page. No install wizard. :(

However, I can access `/BoNeMEAL/robots.txt` just fine, as it displays the text info. .htaccess also seems to be working because it outputs no permission to view `/BoNeMEAL/application`.

Any ideas on how to fix the problem?

**Comment by ftbastler** [comment]
Will look into this when I finally have some spare time again...

**Comment by mibby** [comment]
Great. I'll be here if you need someone to help test why nothing displays. :)

**Comment by mibby** [comment]
@ftbastler Could it have to do with being on CentOS? Most of the required dependencies needed for Laravel are packaged and pre-installed as php-common.

**Comment by ftbastler** [comment]
@mibby I don't know but you could do some searching for Laravel on CentOS...

**Comment by mibby** [comment]
I have no idea. Looked it up, everything should work fine. So not sure why the installation page is a blank page. :(

**Comment by ghost** [comment]
Same thing for me

**Comment by ftbastler** [comment]
What does your webserver log file say?

**Comment by Foreme** [comment]
/var/www/html/BoNeMEAL/application/storage/logs
Only things in here is .gitignore

**Comment by ghost** [comment]
[Mon Nov 30 20:03:49 2015] [error] [client xxx.xx.xxx.xx] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/BoNeMEAL/application/storage/logs/laravel-2015-12-01.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84\nStack trace:\n#0 /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(88): Monolog\Handler\StreamHandler->write(Array)\n#1 /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)\n#2 /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Logger.php(265): Monolog\Handler\AbstractProcessingHandler->handle(Array)\n#3 /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Logger.php(543): Monolog\Logger->addRecord(400, 'exception 'Unex...', Array)\n#4 /var/www/html/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate in /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 84
[Mon Nov 30 20:03:49 2015] [error] [client xxx.xx.xxx.xx] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/BoNeMEAL/application/storage/logs/laravel-2015-12-01.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84\nStack trace:\n#0 /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(88): Monolog\Handler\StreamHandler->write(Array)\n#1 /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)\n#2 /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Logger.php(265): Monolog\Handler\AbstractProcessingHandler->handle(Array)\n#3 /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Logger.php(543): Monolog\Logger->addRecord(400, 'exception 'Symf...', Array)\n#4 /var/www/html/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate in /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 84

**Comment by ftbastler** [comment]
There we go: Permission denied

Check that your permissions are correct:
Folders 755
Files 644

Apart from:
app/storage 777 (or 755 with owner as webserver user)

**Comment by Foreme** [comment]
I did these 2 commands
chmod 0755 /var/www/html/BoNeMEAL
chmod 0750 /var/www/html/BoNeMEAL
(I only have a rough idea of what they actually do :P)
Now it actually loads! no server error 500 but it says "Forbidden"
"You don't have permission to access /BoNeMEAL/index.php on this server."

**Comment by Foreme** [comment]
You can probably already tell I don't fully know what i'm doing, i'm new~
Here is that part of my apache config that references where BoNeMEAL is located

<Directory "/var/www/html">

#
# Possible values for the Options directive are "None", "All",
# or any combination of:
#   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
#
# Note that "MultiViews" must be named *explicitly* --- "Options All"
# doesn't give it to you.
#
# The Options directive is both complicated and important.  Please see
# http://httpd.apache.org/docs/2.2/mod/core.html#options
# for more information.
#
    Options Indexes FollowSymLinks

#
# AllowOverride controls what directives may be placed in .htaccess files.
# It can be "All", "None", or any combination of the keywords:
#   Options FileInfo AuthConfig Limit
#
    AllowOverride All

#
# Controls who can get stuff from this server.
#
    Order allow,deny
    Allow from all

</Directory>

I don't think there is any problems with it

**Comment by Foreme** [comment]
When I was using chmod I wasn't applying it to all files and directories, should I apply 755 to all files and directories in /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog

**Comment by Foreme** [comment]
I haven't touched any .htaccess files since I don't know what i'm doing

**Comment by ghost** [comment]
I finally managed to fix it
chmod 777 /var/www/html/BoNeMEAL

I checked in FileZilla, all files are 644 and all folders are 755

/application/storage (all files and folders) is set to 777

**Comment by ghost** [comment]
[2015-12-02 08:44:26] production.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 19 column email is not unique' in /var/www/html/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Database/Connection.php:362

http://pastebin.com/raw.php?i=vdBfSJFf

**Comment by mibby** [comment]
Re-setting the folder/file permissions to chmod 777 didn't do anything for me. Oh well, guess I'm going to have to give up. :( There are no log files for me.

**Comment by ghost** [comment]
I wonder where ftbastler went

**Comment by ftbastler** [comment]
I'm here... this seems like a sql issue. Can you maybe try to remove the BoNeMEAL table and then re-install it?

**Comment by ftbastler** [comment]
Did you try to re-install BoNeMEAL?

**Comment by ghost** [comment]
Many times

**Comment by ghost** [comment]
I tried deleting database.sqlite, didnt work

**Comment by ftbastler** [comment]
Remove everything and start from scratch with the latest files from here:
https://github.com/ftbastler/BoNeMEAL/archive/master.zip

**Comment by ghost** [comment]
New error
http://pastebin.com/raw.php?i=ZjSmA9QH

[2015-12-07 13:57:45] production.ERROR: exception 'ErrorException' with message 'file_put_contents(/var/www/html/BoNeMEAL/application/.env): failed to open stream: Permission denied' in /var/www/html/BoNeMEAL/application/app/Http/Controllers/InstallController.php:91

**Comment by ftbastler** [comment]
It can't open the file /var/www/html/BoNeMEAL/application/.env

**Comment by ghost** [comment]
.env was named .env.example, so I renamed it and I got past that error but now I get this one.
Also .env will only work with 777

[2015-12-08 16:26:39] production.ERROR: exception 'ErrorException' with message 'file_put_contents(/var/www/html/BoNeMEAL/application/installed.lock): failed to open stream: Permission denied' in /var/www/html/BoNeMEAL/application/app/Http/Controllers/InstallController.php:101

Edit: Nevermind, I made /application 777 so it could create installed.lock, now i've changed it back to 755

**Comment by ghost** [comment]
I'm all good now, not sure about the others who commented here... I kinda just hijacked this issue :P

**Comment by ftbastler** [comment]
Well, the solution is in here for anyone who has that kind of problem.
