### ISSUE TITLE
Language files translated to German

### ISSUE THREAD

**Issue by Townville** [ftbastler/BoNeMEAL#5]
Hello,

i have translated something of BoNeMEAL for my Server so if you want the file, Link is there ;)
If there's anything wrong or someting not (right) translated, don't freak out. I'm only a people, not a machine ;)
To install the language: go to /whereinstalled/application/resources/lang and drag and drop the folder in there.
After that go to /whereinstalled/application/config and open app.php.
Then search these lines:

'locale' => env('APP_LOCALE', 'en'),

'fallback_locale' => 'en',

and change only the first or both to:

'locale' => env('APP_LOCALE', 'de'),
'fallback_locale' => 'de',

Link to the Folder: https://github.com/Townville/GermanBoNeMEAL

**Comment by Townville** [comment]
Just say NO ISSUE

**Comment by ftbastler** [comment]
Thanks a lot!

I didn't expect any contributions at this stage of development, therefor I did not yet write a wiki page on  this topic yet.
Just so you know (for the next time), the perfect way to contribute would have been a pull request - but no offence. ;)

I'm going to include the translation into BoNeMEAL if you agree, so everyone will have it pre-installed and can select it from the installer.

Thanks again.

**Comment by Townville** [comment]
Sry new at Github.
Sure you can.
I Update it if i have free time :D

**Comment by ftbastler** [comment]
Thanks, I commited the files. If you want to make changes to the translations or add new ones fork this repository, make your changes and then submit a pull request.

Thanks again.

**Comment by EvilOlaf** [comment]
Just fork BoNeMEAL and when you're done with updating the language file create a pull request ;)
