### ISSUE TITLE
Error "Whoops, looks like something went wrong."

### ISSUE THREAD

**Issue by yannickkordel** [ftbastler/BoNeMEAL#52]
When I try to install BoNeMEAL I get the error "Whoops, looks like something went wrong" I do not know where the error is. I have followed the instructions exactly. -> yannickko.de/BoNeMEAL

**Comment by ftbastler** [comment]
Please post your log file: https://github.com/ftbastler/BoNeMEAL/wiki/Reporting-issues

**Comment by yannicktf** [comment]
[2015-07-26 13:29:39] production.ERROR: exception 'PDOException' with message 'could not find driver' in /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('sqlite:/var/www...', NULL, NULL, Array)
#1 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/SQLiteConnector.php(37): Illuminate\Database\Connectors\Connector->createConnection('sqlite:/var/www...', Array, Array)
#2 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(58): Illuminate\Database\Connectors\SQLiteConnector->connect(Array)
#3 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(47): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(177): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'local')
#5 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(65): Illuminate\Database\DatabaseManager->makeConnection('local')
#6 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Support/Facades/Schema.php(16): Illuminate\Database\DatabaseManager->connection('local')
#7 /var/www/BoNeMEAL/application/app/Providers/AppServiceProvider.php(25): Illuminate\Support\Facades\Schema::connection('local')
#8 [internal function]: App\Providers\AppServiceProvider->boot()
#9 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#10 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(703): Illuminate\Container\Container->call(Array)
#11 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(685): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AppServiceProvider))
#12 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation{closure}(Object(App\Providers\AppServiceProvider), 14)
#13 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): array_walk(Array, Object(Closure))
#14 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
#15 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(181): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#16 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(199): Illuminate\Foundation\Application->bootstrapWith(Array)
#17 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->bootstrap()
#18 /var/www/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#19 /var/www/BoNeMEAL/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#20 {main}

**Comment by ftbastler** [comment]
Be sure you meet all requirements: https://github.com/ftbastler/BoNeMEAL/wiki/Installation-and-Setup

**Comment by lwatsondev** [comment]
If you still have this issue after installing sqlite3, set the encryption key in applicationconfig/app.php to a random 32 character string. If mcrypt fails for whatever reason, laravel seems to shit the bed when trying to load sqlite3.

**Comment by voigtman** [comment]
I am getting this error, and it's new to me. Bonemeal had been running fine until now.

**Comment by ftbastler** [comment]
Do you have sqlite installed?

**Comment by ftbastler** [comment]
No response. Close.
