### ISSUE TITLE
Improve BoNeMEAL regarding load time with large databases and multiple servers

### ISSUE THREAD

**Issue by Slind14** [ftbastler/BoNeMEAL#53]
https://i.imgur.com/OwbbK1v.png
https://i.imgur.com/WlmxUeN.png
https://i.imgur.com/C2Bcd6e.png

**Comment by ftbastler** [comment]
Thanks for your report. Will look into it.

**Comment by thu2468** [comment]
Can you please fix this

**Comment by ftbastler** [comment]
How many server do you have added to BoNeMEAL?

**Comment by Slind14** [comment]
1 with a few thousand bans

**Comment by ftbastler** [comment]
Ah.. okay. I will try to optimize this by using cron tasks to get stuff done.

**Comment by Slind14** [comment]
looking forward to it

**Comment by oranges13** [comment]
My PR #96 introduces some performance updates that should fix this issue.

**Comment by Slind14** [comment]
Looking good, thank you @oranges13 
The only view which is still running into this issue is "Players".

**Comment by oranges13** [comment]
Depending on how many players you have, fixing that issue may require moving to server-side datatables. That's not impossible, just this app is written with an older version of Laravel then what it currently supports. Definitely in the list of things I want to do, but would be a significant rewrite. I will see if there's anything else I can do to make it more efficient in the mean time.

**Comment by Slind14** [comment]
Great, thank you. The bm_players table has +400k records.

**Comment by oranges13** [comment]
Holywow, yeah -- I'm going to keep developing. As there's been no response from @ftbastler on the PR's I'm going to move to my fork: https://github.com/oranges13/BoNeMEAL

I released all the changes I have made so far as 1.2.0. I need to integrate the commit you referenced above, but I will make a new release for that shortly.

**Comment by Slind14** [comment]
Great, thank you :)
Feel free to cherry pick it.
