### ISSUE TITLE
404 Error during install

### ISSUE THREAD

**Issue by quiquelhappy** [ftbastler/BoNeMEAL#58]
My server have ALL requirements and plugins for work.
When I try to go http://netcraftmc.net/panel/bm2 for setup it jumps to a 404 error.

I know why:
install folder doesn't exist!
Where do I download install folder?

Ussing last BoNeMEAL version.
I was ussing official BM WebUI and working without errors... (http://netcraftmc.net/panel/bm)

<bold>MY .HTACCESS OF /PANEL/BM2 FOLDER.</bold> https://gyazo.com/b6467e43a36aa641d097fdda9ac6a170
<bold>MAIN FOLDER FOR BONEMEAL</bold> https://gyazo.com/91297c9c8e3c78f43ce4ef8a4602f479

**Comment by ftbastler** [comment]
http://netcraftmc.net/panel/bm2/index.php/install works for me (notice the index.php)

**Comment by quiquelhappy** [comment]
hi, PLEASE lots of friends had the same problem, specify it in the wiki :D 
very good UI by the way, keep working on it :+1:
