### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by talkahe** [ftbastler/BoNeMEAL#60]
I was trying to install BoNeMEAL. When I clicked on Continue after insert the configuration it throws an error. 
[Here](https://ghostbin.com/paste/289j5) is the laravel log.

**Comment by ftbastler** [comment]
Which version do you use? The latest stable one or the latest development version?

**Comment by talkahe** [comment]
The latest developement version from this commit https://github.com/ftbastler/BoNeMEAL/commit/de631549300691a8bcb99cb8f0429a4a5a775b06.

**Comment by ftbastler** [comment]
I just tested that and it works fine on my end. Did you follow the docs?
https://github.com/ftbastler/BoNeMEAL/wiki/Installation-and-Setup

**Comment by talkahe** [comment]
Yes, I followed the docs.
