### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by SlayerMarth** [ftbastler/BoNeMEAL#65]
For starters, I'm a serious noob with stuff like this. I'm not sure if I was supposed to do it this way or not, but it's the way I've done other things. So, here goes.

What I did was, I made a subdomain for this to be on.
My normal domain is "http://apex-factions.com"
I made/attempted to install this with "http://ban.apex-factions.com"

Everything went smoothly, uploading and permissions wise. When I went to the page to start the install, it went to "ban.apex-factions.com/install" and I got this. https://gyazo.com/7d01fa46656d4b85ea523abef95b4376

Now, I was completely lost at the RewriteBase part. So that's pretty much where I left off/skipped... 
I don't really know what my host uses as far the php, apache, and what not. Nor do I know what that all is. (I'm used to just moving one or two files, and configuring a self-explanatory configuration.) All of this is pretty much out of my comfort zone. But at the same time, it's actually really important to me because this is one of the last things I need before I can open my server to the public. So I've been trying to get this squared away ASAP, literally.

Do you happen to have any ideas, suggestions, or just flat out know exactly what I should do?

**Comment by ftbastler** [comment]
Try to set your RewriteBase to /
If you go to http://ban.apex-factions.com/index.php/install you see that it indeed works and it appears that you have installed all requirements to run BoNeMEAL.

**Comment by SlayerMarth** [comment]
Oh.. I didn't put the index.php part.Okay, well it works now. But when I go to connect the database BanManager is using, it says

"Notice
Can not connect to database. 

Details:
Can't connect to MySQL server on '69.175.101.66' (110)"

But the information is all correct. Any idea as to why?

**Comment by ftbastler** [comment]
Jeah, your MySQL db probably doesn't allow outside connections.
Does your website and MySQL db run on the same server? Then try to connect to it with 'localhost'.

**Comment by SlayerMarth** [comment]
What would I put in the password field for it?

**Comment by ftbastler** [comment]
The password to access the MySQL db?

**Comment by SlayerMarth** [comment]
To try it with the localhost? Would it be the same as my actual db?

**Comment by SlayerMarth** [comment]
Okay, here's what my hosting told me. 

"That is correct, it doesn't allow outside MySQL connections. To allow it, you must white list the external device trying to access the database by entering that device's IP(s) into the Remote MySQL menu found in your cPanel menu. Only IPs listed there would be allowed access to the database."

I'm not entirely sure what I'm really supposed to do here. How would I whitelist BoNeMEAL? Sorry if I'm sounding really slow and stupid. As I said, I'm a serious noob with stuff like this. So I'm trying to learn to avoid future problems. I thank you for bearing with me though.

**Comment by ftbastler** [comment]
You would whitelist the IP of the web server where BoNeMEAL is running (which is 104.219.248.76 in your case). You can ask your hosting partner for help with that.

**Comment by SlayerMarth** [comment]
Ah, okay. 
Well, I just needed the ip. I know how to do the rest I believe. I'll give that a go and let you know how things turn out.

**Comment by SlayerMarth** [comment]
Same reaponse. Not being able to connect to the database.

**Comment by SlayerMarth** [comment]
Anything?

**Comment by ftbastler** [comment]
No sorry, I can't help you. I just depends a lot on your hosting environment.
You can try to do some google searches about how to allow external access to a mysql db.

**Comment by SlayerMarth** [comment]
Okay, well thanks for your help. Ill try googling my issue. If I don't come up with anything, I'll just scrap all this and go back to MaxBans and not use a website UI type thing.Thanks again.

**Comment by ftbastler** [comment]
You can try https://github.com/BanManagement/BanManager-WebUI
BoNeMEAL is meant for more experienced users.

**Comment by SlayerMarth** [comment]
I did, and I'm having the same issue with that too.
I set up BoNeMEAL on a "ban" subdomain, and setup the BM-WebUI on a "bans" domain.

http://bans.apex-factions.com/

As you can pretty clearly see there, It's trying to use a localhost, but I'm not sure why, nor do I know how to fix it for one. And two, it's not connecting to the MySQL, same as BoNeMEAL isn't. I've been talking with them in a issues post about it. But, no offense to them, they aren't all that quick at responding. Which is why I ultimately came here to give BoNeMEAL a go. It looked better for one, and actually seemed easier to set up. So I thought maybe I'd have better luck. Obviously it has to be something on my end if it's not working for ANY ban plugin web integrations.

**Comment by SlayerMarth** [comment]
Just stopping back by to say that I resolved the issue. Me and my hosting were doing some trial and error type things. Ultimately they had to reset the backend settings on my account to get it working. 

Just thought I'd leave that message for anyone else who might have the same issue in the future.

**Comment by ftbastler** [comment]
@SlayerMarth Great to hear that it works now! :)
