### ISSUE TITLE
Random Search Error

### ISSUE THREAD

**Issue by jonathonyoungquist** [ftbastler/BoNeMEAL#67]
On the main page where all users can search punishments, sometimes you will get the page "Whoops, looks like something went wrong." Thing is, sometimes it works, sometimes it doesn't.

**Comment by ftbastler** [comment]
Thanks for the info. Can I get additional information?
https://github.com/ftbastler/BoNeMEAL/wiki/Reporting-issues

**Comment by jonathonyoungquist** [comment]
There are absolutely no error logs generated, odd.

**Comment by Torbikini** [comment]
http://pastebin.com/tvXcVpbG
