### ISSUE TITLE
BanManager dev won't change this so can you?

### ISSUE THREAD

**Issue by ghost** [ftbastler/BoNeMEAL#68]
https://github.com/BanManagement/BanManager/issues/475
I asked the banmanager dev to add [PlayerId] as a variable so I can use the website feature with BoNeMEAL, he did it like this "5a8ac984-62b3-473f-9cdf-99a5ac49cd86" which doesn't work in BoNeMEAL. I asked him to change it (would have been very easy for him to do) but he decided to make life hard and make me come here. If you could make it so "5a8ac984-62b3-473f-9cdf-99a5ac49cd86" and "5a8ac98462b3473f9cdf99a5ac49cd86" both work in website links that would be amazing.

**Comment by EvilOlaf** [comment]
Should not be that difficult to strip the hyphen on this end too I think?

**Comment by ghost** [comment]
Thanks ftbastler, I even made the change for the BanManager guy and he just ignored my change request @-@

**Comment by oranges13** [comment]
Hi @Foreme can you elaborate more on where the UUID attribute needs to be changed? Thank you.
