### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by KillerAntMC** [ftbastler/BoNeMEAL#69]
Hello, when ever I click "Continue" in the configuration page of the installation, the page freezes and I receive an error. This is the error log:

http://pastebin.com/9tMXczDt

**Comment by ftbastler** [comment]
The error says PHP can't write to /var/www/html/bans/application/.env
Please ensure that your file/folder permissions are correct.

**Comment by KillerAntMC** [comment]
The file ".env" wasn't there so I created it and gave it the proper permissions. I am now receiving this error: http://pastebin.com/gV5mNxjT

**Comment by ftbastler** [comment]
Remove and re-install BoNeMEAL, but before you click on install create the .env file.

**Comment by KillerAntMC** [comment]
Thanks it worked.
