### ISSUE TITLE
Can you make it so that admin cant acccess the server configuration?

### ISSUE THREAD

**Issue by thu2468** [ftbastler/BoNeMEAL#7]
Can you make it so that admin cant acccess the server configuration?

**Comment by thu2468** [comment]
Or a way to make more user groups

**Comment by EvilOlaf** [comment]
Like this: https://github.com/BanManagement/BanManager-WebUI/issues/54 ?

**Comment by thu2468** [comment]
yea like that but right now there only four different group;
Normal
Moderator
Admin
Superuser
Is there a way to add a custom group? or edit one of those group perms?

**Comment by ftbastler** [comment]
Thanks for your request. I will see what I can do about that.
