### ISSUE TITLE
On installation: Whoops, Something went wrong

### ISSUE THREAD

**Issue by mcreef** [ftbastler/BoNeMEAL#70]
Hi,
In my Installation is an error. Here is the screen:
http://i.imgur.com/PJNtF9b.png

Here is my log:

<script src="https://gist.github.com/logtainment/d2513d64d12098cca27c.js"></script>

https://gist.github.com/logtainment/d2513d64d12098cca27c

**Comment by ftbastler** [comment]
See #69

**Comment by logtainment** [comment]
Thanks. Can I change this:

Am I being detained?!
With BoNeMEAL you can check your punishments, when and why you got them and when they will expire.
