### ISSUE TITLE
Cant open Admin Panel after deleting Player in Phpmyadmin

### ISSUE THREAD

**Issue by mcreef** [ftbastler/BoNeMEAL#72]
Hi,
I've deleted 3 Players in the Bans database in my phpmyadmin. After that i can't access the Admin index. The Other admin Pages are working,
Here's my log with the error:

http://pastebin.com/xQA9jsT4

**Comment by ftbastler** [comment]
Uhhh... yeah that could mean you broke it...

**Comment by mcreef** [comment]
What can I do?

**Comment by mcreef** [comment]
Okay. I've fixed the Problem. I've imported the backup from my Phpmyadmin in bm_players
