### ISSUE TITLE
Using too much memory

### ISSUE THREAD

**Issue by JKnetz** [ftbastler/BoNeMEAL#73]
I have my PHP memory limit set as default, 128M

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes)

It works when I allow it to use unlimited memory but it looks like theres a leak.

**Comment by JKnetz** [comment]
I do have about 5-6 servers with large databases.

**Comment by ftbastler** [comment]
Yes, I am aware of this issue but #66 needs priority.

**Comment by ftbastler** [comment]
Also see #53
