### ISSUE TITLE
Cannot Connect to database, connection timed out

### ISSUE THREAD

**Issue by itsfolf** [ftbastler/BoNeMEAL#76]
When I try to add my server I always get Cannot Connect to database, connection timed out, at sites like http://www.phpmyadmin.co/ the dB works fine.

**Comment by acidbyt3** [comment]
That's not really much to go on, if you could post some more detailed information that would be helpful.

Have you allowed remote connections on the database host and whitelisted the address you're attempting to connect from? This can be done on the database's host cPanel
