### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by antman56** [ftbastler/BoNeMEAL#79]
Earlier yesterday, I was able to successfully setup my BoNeMEAL site and it connected successfully with my sql database and all... but today when I tried to access my site, I went to homepage `mysite.com/index.php`, and it works fine, but when i try to go to any other page (for example when i type in my username to test and click check) it navigates my browser to `mysite.com/index.php/players/search` and it comes up with the error saying:
Whoops, looks like something went wrong.

This happens when I attempt to access any url (other than `index.php`). 
I have the log file (with the error):

`[2016-03-31 14:08:25] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Connection refused' in /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('mysql:host=192....', '**REMOVED FOR PRIVACY**', '**REMOVED FOR PRIVACY**', Array)
#1 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=192....', Array, Array)
#2 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(58): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(47): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(177): Illuminate\Database\Connectors\ConnectionFactory->make(Array, '1')
#5 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(65): Illuminate\Database\DatabaseManager->makeConnection('1')
#6 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3146): Illuminate\Database\DatabaseManager->connection('1')
#7 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3112): Illuminate\Database\Eloquent\Model::resolveConnection('1')
#8 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1887): Illuminate\Database\Eloquent\Model->getConnection()
#9 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1828): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#10 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1802): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#11 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(637): Illuminate\Database\Eloquent\Model->newQuery()
#12 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/app/Http/Controllers/ApiController.php(34): Illuminate\Database\Eloquent\Model::on('1')
#13 [internal function]: App\Http\Controllers\ApiController->searchPlayerNameAll('sa')
#14 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#15 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('searchPlayerNam...', Array)
#16 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\ApiController), Object(Illuminate\Routing\Route), 'searchPlayerNam...')
#17 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#18 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/app/Http/Middleware/VerifyInstalled.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#20 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\VerifyInstalled->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#22 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\ApiController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'searchPlayerNam...')
#25 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'searchPlayerNam...')
#26 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#27 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#29 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#31 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#34 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#35 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http{closure}(Object(Illuminate\Http\Request))
#37 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#39 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/app/Http/Middleware/VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#42 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#44 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#46 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#48 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#50 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#52 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /home/vol4_1/my.vg/myvg_17773147/htdocs/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#55 /home/vol4_1/my.vg/myvg_17773147/htdocs/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#56 {main}  `

**Comment by miguel456** [comment]
It seems your database was offline at the time...
