### ISSUE TITLE
Whoops, it looks like something went wrong! (6th time it has happened to me. I just keep reinstalling it)

### ISSUE THREAD

**Issue by Skizzy77** [ftbastler/BoNeMEAL#80]
Hi there! Whenever I try to do things like access the admin panel, I get this error: http://prntscr.com/br4bdx
Same thing when searching for a player: http://prntscr.com/br4b88

I am hoping anyone can help me. I am not sure what is causing this. I have used this program on previous servers and never had an issue.

Check it out: http://www.scorchgamez.net/bans/index.php

**Comment by Skizzy77** [comment]
Happened again.

**Comment by oranges13** [comment]
Can you provide server logs to help diagnose the issue? You can find them under `application/storage/logs/`

**Comment by oranges13** [comment]
Can you try and install the most recent version and let us know if you are still having this issue? Please reopen if so.

**Comment by Skizzy77** [comment]
I have moved away from using Bonemeal as I began construction of a custom solution (although I eventually did get it to work).
