### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by ChimpGamer** [ftbastler/BoNeMEAL#81]
Whoops, looks like something went wrong.
getting that message when i try
http://lx01.cremers.local/bans/index.php/install
pls help

**Comment by ChimpGamer** [comment]
ahh i think this source is inactive

**Comment by miguel456** [comment]
I cannot access a .local website! (Unless you and me have a direct VPN connection lmao)
Unless you forward port 80 and get a hostname, that link is not gonna work. Get something like lx01.cremers.com or get a free subdomain.
Anyway if you are getting an error you should be pasting it on PasteBin or Hastebin, not showing it on your own site...
If that "Whoops" error only shows the blank page, get Laravel's logfile in /application/storage/logs
