### ISSUE TITLE
panel malfunction

### ISSUE THREAD

**Issue by Jerlag01** [ftbastler/BoNeMEAL#84]
Panel malfunctions when running it on a windows server 2012 R2 with IIS 8.
The IIS is running latest MySQL database and PHP 5.5.6,
however it malfunctions when you call it up (Returns with 404: Oops somethng went wrong!)
The panel  does work on the USB webserver software with PHP 5.4.17 .

I hope you can help me.

**Comment by miguel456** [comment]
You're using IIS, and BoNeMEAL doesn't natively support it. 
The best way you can make things work is by writing a web.config file for the application.
Here, you can use what I am using now:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="2f1" stopProcessing="true">
                    <match url="^bans/(.*)/$" />
                    <action type="Rewrite" url="/bans//{R:1}" />
                </rule>
                <rule name="Remove trailing slash" stopProcessing="true">
                    <match url="^bans/" />
                    <action type="Rewrite" url="/bans/index.php" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```
**!!!! CHANGE THE REWRITE BASE URL AND ACCESS THE INSTALLATION WITH /PATH/TO/INSTALL/INDEX.PHP , /PATH/TO/INSTALL/ WILL NOT WORK! !!!**

For example, if your installation path is /serverbans, you would change the URLS to something like this, in the above code:
`<action type="Rewrite" url="/serverbans/index.php`.

**Make sure that IIS has support for URL rewriting enabled.**

And what do you mean by USB server software? Apache or something?

**Comment by ftbastler** [comment]
Resolved.

**Comment by Jerlag01** [comment]
usb webserver was free software provided by a company to turn your usb into a simple plug and play web server. basicly the same as xampp, the only difference between the 2 is that the usb webserver software doesn't need to be installed and xampp does. this way you can work everywhere on any laptop on your website and take it anywhere you want

**Comment by oranges13** [comment]
Hey Jerlag01 -- IIS is not the same as XAMPP and does have several configuration differences. Are you still having this issue?

**Comment by Jerlag01** [comment]
@oranges13 I know that. I was just replying on the queston from ftbbastler that he asked a couple of years ago, which i never got a notification from
