### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by Botanistt** [ftbastler/BoNeMEAL#85]
What am I supposed to edit in order to be able to access site using https instead of http?
When I'm using http everything is fine but when I'm using https everything is being loaded through http.
Advice?

**Comment by miguel456** [comment]
My installation is running with SSL perfectly. You need to enforce access via SSL with your webserver software (i.e. on Microsoft IIS you'd do so with a specifically written web.config file. The same applies for Apache and so on).

**Comment by ClockProgramming** [comment]
My installation loaded this up perfectly with SSL.

**Comment by Legoman99573** [comment]
i did fork this a while back, i could redo how styling is loaded
