### ISSUE TITLE
I'm getting just white pages

### ISSUE THREAD

**Issue by 123hotdog1100** [ftbastler/BoNeMEAL#86]
[Wed Jan 25 22:54:45.789247 2017] [:error] [pid 5417] [client PERSONAL IP(SORRY):63310] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/html/BoNeMEAL/application/storage/logs/laravel-2017-01-25.log" could not be opened: failed to open stream: Permission denied in /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87\nStack trace:\n#0 /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(88): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Logger.php(289): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Logger.php(565): Monolog\\Logger->addRecord(400, 'UnexpectedValue...', Array)\n#4 /var/www/html/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Han in /var/www/html/BoNeMEAL/application/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 87 
this is the error im getting I've tried everything to change it to allow perms but nothing works i would love if i could get a bit of help on the matter

**Comment by miguel456** [comment]
I'm writing a PHP application to fix your problem. Hold on tight! 
In the meantime, could you provide some more details? PHP error log, output of `ls -l` and things like that?
By the way: The developer has **abandoned** this project and hasn't set return date, and so far I'm the only one trying to help people in bugreports.

**Comment by 123hotdog1100** [comment]
Thank you for the help I am very gratefull for it
root@vmi100788:/var/www/html/BoNeMEAL# ls -l
total 40
drwxr-xr-x 9 root root 4096 Jan 26 22:51 application
-rw-r--r-- 1 root root  331 Jan 26 22:51 CONTRIBUTING.md
drwxr-xr-x 2 root root 4096 Jan 26 22:51 fonts
drwxr-xr-x 2 root root 4096 Jan 26 22:51 images
-rw-r--r-- 1 root root 1795 Jan 26 22:51 index.php
-rw-r--r-- 1 root root  858 Jan 26 22:51 LICENSE.md
-rw-r--r-- 1 root root 1016 Jan 26 22:51 README.md
-rw-r--r-- 1 root root   37 Jan 26 22:51 robots.txt
drwxr-xr-x 2 root root 4096 Jan 26 22:51 scripts
drwxr-xr-x 2 root root 4096 Jan 26 22:51 styles

http://pastebin.com/vU7bm1s3

**Comment by oranges13** [comment]
`failed to open stream: Permission denied` error is because your web server does not have permission to write to your log file. Check the permissions in `application/storage/logs` and make sure your webserver user can write to that directory (to create new log files)
