### ISSUE TITLE
Support MySQL with SSL enforced

### ISSUE THREAD

**Issue by runelynx** [ftbastler/BoNeMEAL#87]
Hello,

I recently updated my game server's MySQL to the latest version which is VERY verbose if you don't utilize SSL. So, I enabled it. Everything is great now except Bonemeal does not seem to support connecting to a MySQL server with SSL enabled. I have the keys on the web server ready to go but am not sure how to configure it. 

In the meantime, Bonemeal on my website (which previously worked fine) now just says

Whoops, looks like something went wrong.

I've looked into the MySQL Illuminate Connector.php class and it doesn't really echo any commonly used MySQL connections I can find on the web or that I have experience with in my own PHP.

Halp!!

**Comment by miguel456** [comment]
Bonemeal has been abandoned by it's author. Since ftbastler is inactive, you will not be getting any support. The file you looked at is a part of the Laravel framework, which Bonemeal is using. Searching in its lines for an error coming from a project that uses it is useless.

PHP Uses MySQLi or PDO to connect to databases and they are indifferent to SSL (Correct me if I'm wrong). 
I have no knowledge of this codebase so I cannot help you. I'm planning on forking and updating this repository so in a few months time you can check my profile.
Regards,
Miguel.

**Comment by runelynx** [comment]
Hi @miguel456 - 
Curious if you're still planning on updating a fork? :)

**Comment by oranges13** [comment]
Hi @runelynx I've been submitting PR's to try and fix issues and I can take a look at yours if it's still an issue for you. Please let me know.

**Comment by runelynx** [comment]
It is; I would love to have Bonemeal working again!!

**Comment by oranges13** [comment]
Hi @runelynx ! Sorry for the delay. I have pushed code to a branch for you to test.

1. **If you currently have BoNeMEAL installed, please make a backup of your current installation directory before proceeding.**
2. Download the zip of the branch here: https://github.com/ftbastler/BoNeMEAL/archive/87-mysql-ssl-support.zip
3. The files will expand in a subfolder named the same as the branch. You can rename this folder to place it in the same location as your current installation, or copy the contents of that folder into your current installation. (If you are attempting to install this from scratch, simply rename the folder to whatever you need for your webserver's configuration -- and make sure to adjust the `.htaccess` file `RewriteBase` directive appropriately.)
4. Overwrite any modified files -- but make sure to double check your configuration in your `.htaccess` is the same from your backup.

Please let me know if you have issues with this branch, or have any other questions or concerns.

If anyone else would like to help test this updated branch, please follow the steps above. This introduces changes that cannot be reverted once installed, so please ***MAKE A BACKUP*** if you are currently using BoNeMEAL to be able to go back to your original version if you have issues.

**Comment by runelynx** [comment]
hiya -
thanks a lot for this! 

Having trouble installing it though. The folder "banmgmt" holds all contents of the zip and sits within my root public html folder... so I set the Rewrite to "/banmgmt".  Application folder is now 750 and /application/storage is 755.   But when I run  /index.php/install... I get

Whoops, looks like something went wrong.
Whoops, looks like something went wrong.

Any hints?

**Comment by oranges13** [comment]
1. Is there any log files in application/storage/logs/ ? Can you post the most recent one using a pastebin? (paste.ubuntu.com)
2. Check out my installation tips posted in #92 -- I just re-downloaded the branch from scratch into a virtual box and had the same issue that I outlined there.

**Comment by runelynx** [comment]
https://paste.ubuntu.com/p/Q6XwtvkSjp/

In short:

[2019-07-14 14:13:05] production.ERROR: ErrorException: Function mcrypt_get_iv_size() is deprecated in /home/runicp5/public_html/runicparadise/BoNeMEAL/application/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:303

**Comment by runelynx** [comment]
Tried following the steps in #92 link above; I get a PDO error. I think I'm just not meant to use this web app. 

[runicp5@ecbiz213 BoNeMEAL]$ cd application
[runicp5@ecbiz213 application]$ php artisan key:generate

  [PDOException]
  could not find driver

**Comment by oranges13** [comment]
Aha! The `Function mcrypt_get_iv_size() is deprecated` I know is an issue with php7.1 -- this is using a very old version of Laravel and really wants to use 5.6, howver I'm working on an updated version that will actively support newer versions of PHP. You may be able to fix that issue with this: https://stackoverflow.com/a/41661835

I have also seen the driver not found issue if your command line isn't using the same PHP version as your webserver. Basically the web server knows your database driver exists but your command line is using a different PHP environment.

Alas, if it was working before updating to the new code it may just be that it's so out of date now that it doesn't want to work. As soon as we have the newer version up, I'll let you know!

**Comment by runelynx** [comment]
You sir, are correct! I just updated cpanel to use PHP 5.6 and the errors are gone. Now to try configuring my server and see if it works :)

**Comment by oranges13** [comment]
Hi @runelynx -- I have updated this branch with the most recent version that supports PHP 7+ so it should operate on most hosts until I get a chance to rewrite the entire thing.

Can you test with the most recent version of the branch and let me know if it meets your needs?

**Comment by runelynx** [comment]
After years, really, BoNeMEAL is working for us again. The kudos from my staff is yours, @oranges13  :)

![image](https://user-images.githubusercontent.com/5877481/68523698-73779c00-0271-11ea-897b-59ddee6b3415.png)

![image](https://user-images.githubusercontent.com/5877481/68523701-78d4e680-0271-11ea-91a1-f3d5c86ef120.png)

**Comment by oranges13** [comment]
I am SO PLEASED that this works! I'll merge this to master and make it an official release soon!
