### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by redstonedesigner** [ftbastler/BoNeMEAL#88]
My main directory is "/BoNeMEAL" (where it is installed)

However, when I do anything, it gives me
![image](https://user-images.githubusercontent.com/29328096/31228804-a7b67036-a9d6-11e7-822d-0ad7b3f5ed9b.png)

It is very annoying.

Could I have some help please?

Thanks in advance,
Redstone

**Comment by miguel456** [comment]
Are you still experiencing this issue?
@redstonedesigner

**Comment by oranges13** [comment]
You need to provide logs to help debug the issue. You can find your error logs in `application/storage/logs` in your Bonemeal directory.
