### ISSUE TITLE
I'm forking the project

### ISSUE THREAD

**Issue by miguel456** [ftbastler/BoNeMEAL#89]
Since the project is dead, I'm forking it fix all the existing bugs.
You can find my fork https://github.com/miguel456/BoNeMEAL <- here.

I won't be adding new features at least until I've gotten grip of the code.
I hope you don't mind @ftbastler, I'll be following the existing code's license of course.

- Miguel

**Comment by JeremyGuinn** [comment]
Miguel, I’ve gotten quite a bit fixed on a dev environment. I’ve updated laravel to 5.6 and using php 7.2, which requires quite a few changes to fbastlers source to work with the new laravel. The website installer works properly now, and the non autherized sections work correctly. The next thing I’m working on getting done is the authentication controller.

**Comment by ftbastler** [comment]
Sure, go ahead. You can propose a pull request and I will be happy to check it out.

**Comment by miguel456** [comment]
Oh. I didn't think you were going to be back. That's a good motivation for me here, now that I have more free time. 
Time to inspect some code (:
