### ISSUE TITLE
Some files are not uploading?

### ISSUE THREAD

**Issue by Vidsify** [ftbastler/BoNeMEAL#9]
Hello,

I have a couple of files which are not showing up in my FileManager in CPanel even though they have been uploaded. One of these files is the .htaccess file.

See this screenshot of what I mean:
http://prntscr.com/74bzxu
http://prntscr.com/74c05e

**Comment by EvilOlaf** [comment]
Pretty sure this issue is not related to BoNeMEAL.

To simply hide files on *NIX-based operating systems just add a dot at the very beginning of a filename. You need to explicitly show all files in a directory, usually hidden files are not shown.
To do that check your cPanel manual.

**Comment by Vidsify** [comment]
Thanks. This issue has been fixed :)
