### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by riftens** [ftbastler/BoNeMEAL#90]
![image](https://user-images.githubusercontent.com/41445594/43364660-3f80ed64-92e4-11e8-8095-33f7e02585d3.png)
followed all the instructions and still running into this issue

**Comment by oranges13** [comment]
Did you update the `RewriteBase` directive in the .htaccess file?

**Comment by oranges13** [comment]
If you are still having this issue, can you try installing the latest release and let us know if you continue to have issues?
